services:
  flower:
    image: mher/flower:0.9.7
    container_name: flower
    restart: always
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - '5555:5555'
    depends_on:
      - redis